export { default as Benefits } from './Benefits.svelte';
export { default as Buy } from './Buy.svelte';
export { default as Buy2 } from './Buy2.svelte';
export { default as Buy3 } from './Buy3.svelte';
export { default as Buy4 } from './Buy4.svelte';
export { default as Hero } from './Hero.svelte';
export { default as Intro } from './Intro.svelte';
export { default as Stats } from './Stats.svelte';
export { default as Faq } from './Faq.svelte';
